feat(buildtype ui tests): add 1 positive and 1 negative tests
Iliandr123/RestAssured_API_Testing pull request #5
Opened 2024-11-04 07:51 UTC by Iliandr123

2024-11-10 22:13 UTC, nobugs-me requested changes
Привет! 

Не вижу самих тестов в PR, добавишь, пожалуйста?

2024-11-11 07:49 UTC, Iliandr123 commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
Вот эти тесты

2024-11-11 07:50 UTC, Iliandr123 commented
@nobugs-me 
Привет! Да, они и так есть в PR)
Вот ссылка на них в ветке [homework-ui-test](https://github.com/Iliandr123/RestAssured_API_Testing/tree/homework-ui-test):
https://github.com/Iliandr123/RestAssured_API_Testing/blob/homework-ui-test/src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java

2024-11-12 14:16 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-12 14:16 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
Странно, теперь вижу!

2024-11-12 14:16 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateBuildTypeTest.java
> +        softy.assertTrue(CreateBuildConfigurationPage.hasErrorMessage("Build configuration with name \"%s\" already exists in project: \"%s\""
Отлично! Не хватает проверки на уровне API, что сущность не создалась.

2024-11-23 09:22 UTC, merged